import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { bundleBrowser } from './build-browser';
import { ROOT, isMain } from './gen-lib';

type Role = 'script' | 'css' | 'font' | 'license' | 'schema';

interface ManifestFile {
  path: string;
  source: string;
  sha256: string;
  bytes: number;
  role: Role;
}

/** `path` is where a consumer copies the file; `source` is its path inside the package. */
const ENTRIES: { path: string; source: string; role: Role }[] = [
  { path: 'dravenviz.browser.js', source: 'dist/dravenviz.browser.js', role: 'script' },
  {
    path: 'dravenviz.browser.js.LEGAL.txt',
    source: 'dist/dravenviz.browser.js.LEGAL.txt',
    role: 'license',
  },
  { path: 'dravenviz.css', source: 'dist/dravenviz.css', role: 'css' },
  {
    path: 'fonts/NotoSans-Regular.woff2',
    source: 'assets/fonts/NotoSans-Regular.woff2',
    role: 'font',
  },
  {
    path: 'fonts/NotoSans-SemiBold.woff2',
    source: 'assets/fonts/NotoSans-SemiBold.woff2',
    role: 'font',
  },
  { path: 'fonts/noto-sans.css', source: 'assets/fonts/noto-sans.css', role: 'font' },
  { path: 'fonts/OFL.txt', source: 'assets/fonts/OFL.txt', role: 'license' },
  {
    path: 'schema/viz-spec-v1.schema.json',
    source: 'schema/viz-spec-v1.schema.json',
    role: 'schema',
  },
];

function describeFile(entry: (typeof ENTRIES)[number]): ManifestFile {
  const bytes = readFileSync(path.join(ROOT, entry.source));
  return {
    path: entry.path,
    source: entry.source,
    sha256: createHash('sha256').update(bytes).digest('hex'),
    bytes: bytes.length,
    role: entry.role,
  };
}

/** Writes `dist/asset-manifest.json` (design section 13). Every listed file must already exist. */
export function writeManifest(): void {
  const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')) as {
    name: string;
    version: string;
  };
  const files = ENTRIES.map(describeFile);
  const manifest = { manifestVersion: 1, package: pkg.name, version: pkg.version, files };
  writeFileSync(
    path.join(ROOT, 'dist/asset-manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
}

interface BundledPackage {
  name: string;
  version: string;
  license: string;
  licenseText: string;
}

/** The package directory and name of an esbuild input path inside node_modules, or undefined. */
function packageOf(input: string): { dir: string; name: string } | undefined {
  const marker = 'node_modules/';
  const at = input.lastIndexOf(marker);
  if (at === -1) return undefined;
  const rest = input.slice(at + marker.length).split('/');
  const name = rest[0]?.startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0];
  if (name === undefined) return undefined;
  return { dir: input.slice(0, at + marker.length) + name, name };
}

function licenseTextOf(dir: string): string {
  const abs = path.join(ROOT, dir);
  const file = readdirSync(abs).find((f) => /^(licen[cs]e|copying)(\.[a-z]+)?$/i.test(f));
  return file === undefined ? '' : readFileSync(path.join(abs, file), 'utf8').trim();
}

/** Every package that ends up in the browser bundle, found by walking esbuild's metafile inputs. */
async function bundledPackages(): Promise<BundledPackage[]> {
  const meta = await bundleBrowser(false);
  const dirs = new Map<string, string>();
  for (const input of Object.keys(meta.inputs)) {
    const p = packageOf(input);
    if (p !== undefined) dirs.set(p.name, p.dir);
  }
  const out: BundledPackage[] = [];
  for (const [name, dir] of [...dirs].sort(([a], [b]) => a.localeCompare(b))) {
    const pj = JSON.parse(readFileSync(path.join(ROOT, dir, 'package.json'), 'utf8')) as {
      version: string;
      license?: string;
    };
    out.push({
      name,
      version: pj.version,
      license: pj.license ?? 'UNKNOWN',
      licenseText: licenseTextOf(dir),
    });
  }
  return out;
}

/** Writes THIRD_PARTY_NOTICES.md: bundled npm packages plus the Noto Sans font (OFL-1.1). */
export async function writeNotices(): Promise<void> {
  const packages = await bundledPackages();
  const ofl = readFileSync(path.join(ROOT, 'assets/fonts/OFL.txt'), 'utf8').trim();
  const lines: string[] = [
    '# Third-party notices',
    '',
    'DravenViz itself is UNLICENSED. The browser bundle (`dist/dravenviz.browser.js`) and the',
    'package assets contain the third-party software listed below. This file is generated by',
    '`scripts/build-manifest.ts --notices` from `node_modules/*/package.json` and the license',
    'files of every package esbuild bundles into the browser bundle. Do not edit it by hand.',
    '',
    '## Summary',
    '',
    '| Package | Version | License |',
    '| --- | --- | --- |',
    ...packages.map((p) => `| ${p.name} | ${p.version} | ${p.license} |`),
    '| Noto Sans (font) | 2.015 | OFL-1.1 |',
    '',
  ];
  for (const p of packages) {
    lines.push(`## ${p.name} ${p.version}`, '', `License: ${p.license}`, '');
    lines.push(
      p.licenseText === ''
        ? '(No license file ships with this package; the license above is the SPDX expression declared in its package.json. Its bundled d3 modules are listed separately.)'
        : indent(p.licenseText),
      '',
    );
  }
  lines.push(
    '## Noto Sans (font files in assets/fonts)',
    '',
    'License: OFL-1.1',
    '',
    indent(ofl),
    '',
  );
  writeFileSync(path.join(ROOT, 'THIRD_PARTY_NOTICES.md'), lines.join('\n'));
}

const indent = (text: string): string =>
  text
    .split('\n')
    .map((l) => (l === '' ? '' : `    ${l.trimEnd()}`))
    .join('\n');

if (isMain(import.meta.url)) {
  if (process.argv.includes('--notices')) {
    await writeNotices();
  } else {
    if (!existsSync(path.join(ROOT, 'dist/dravenviz.browser.js'))) {
      throw new Error('Run the browser bundle step first (dist/dravenviz.browser.js is missing).');
    }
    writeManifest();
  }
}
